import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Girish",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Gautam",
      email: "user@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      image: "https://m.media-amazon.com/images/I/41ZGJxnJu1S._AC_SY200_.jpg",
      name: "Samsung M32",
      price: 12000,
      rating: 3.5,
      countInStock: 3,
      category: 'Mobiles',
      brand: 'Samsung',
      description: 'Mobile with 64GB| 4GB RAM| 5000mah | 16px front cam | 64px back cam',
      numReviews: 634,
    },
    {
      image: "https://m.media-amazon.com/images/I/413u56t+CiL._AC_SY200_.jpg",
      name: "One plus Nord CE 2 Lite 5G(Blue Tide, 6GB RAM,128GB storage)",
      price: 18000,
      rating: 4.5,
      countInStock: 0,
      category: 'Mobiles',
      brand: 'One Plus',
      description: 'Mobile with 64GB| 4GB RAM| 5000mah | 16px front cam | 64px back cam',
      numReviews: 852,
    },
    {
      image: "https://m.media-amazon.com/images/I/41CkKbseMGL._AC_SY200_.jpg",
      name: "Samsung S20",
      price: 11000,
      rating: 3.5,
      countInStock: 3,
      category: 'Mobiles',
      brand: 'Samsung',
      description: 'Mobile with 64GB| 4GB RAM| 5000mah | 16px front cam | 64px back cam',
      numReviews: 25,
    },
    {
      image: "https://m.media-amazon.com/images/I/41ZGJxnJu1S._AC_SY200_.jpg",
      name: "One plus Nord Smart Watch",
      price: 20000,
      rating: 4.5,
      countInStock: 6,
      category: 'Mobiles',
      brand: 'One Plus',
      description: 'Mobile with 64GB| 4GB RAM| 5000mah | 16px front cam | 64px back cam',
      numReviews: 504,
    },
    {
      image: "https://m.media-amazon.com/images/I/413u56t+CiL._AC_SY200_.jpg",
      name: "One plus Nord special",
      price: 22000,
      rating: 4.0,
      countInStock: 8,
      category: 'Mobiles',
      brand: 'One Plus',
      description: 'Mobile with 64GB| 4GB RAM| 5000mah | 16px front cam | 64px back cam',
      numReviews: 158,
    },
    {
      image: "https://m.media-amazon.com/images/I/413u56t+CiL._AC_SY200_.jpg",
      name:
        "One plus Nord pro",
      price: 18000,
      rating: 4.5,
      countInStock: 10,
      category: 'Mobiles',
      brand: 'One Plus',
      description: 'Mobile with 64GB| 4GB RAM| 5000mah | 16px front cam | 64px back cam',
      numReviews: 200,
    },
    {
      image: "https://m.media-amazon.com/images/I/41CkKbseMGL._AC_SY200_.jpg",
      name: "Samsung Galaxy",
      price: 11000,
      rating: 3.5,
      countInStock: 3,
      category: 'Mobiles',
      brand: 'Samsung',
      description: 'Mobile with 64GB| 4GB RAM| 5000mah | 16px front cam | 64px back cam',
      numReviews: 100,
    },
    {
      image: "https://m.media-amazon.com/images/I/41d69zua5LL._AC_SY200_.jpg",
      name: "One plus smart watch ",
      price: 20000,
      rating: 4.5,
      countInStock: 4,
      category: 'Mobiles',
      brand: 'One Plus',
      description: 'Mobile with 64GB| 4GB RAM| 5000mah | 16px front cam | 64px back cam',
      numReviews: 44,
    },
  ],
};

export default data;
